//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravletAgence.Web.VisaInfo {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtVisa_id;
		protected global::System.Web.UI.WebControls.TextBox txtGroupNo;
		protected global::System.Web.UI.WebControls.TextBox txtName;
		protected global::System.Web.UI.WebControls.TextBox txtEnglishName;
		protected global::System.Web.UI.WebControls.TextBox txtSex;
		protected global::System.Web.UI.WebControls.TextBox txtBirthday;
		protected global::System.Web.UI.WebControls.TextBox txtPassportNo;
		protected global::System.Web.UI.WebControls.TextBox txtLicenceTime;
		protected global::System.Web.UI.WebControls.TextBox txtExpiryDate;
		protected global::System.Web.UI.WebControls.TextBox txtBirthplace;
		protected global::System.Web.UI.WebControls.TextBox txtIssuePlace;
		protected global::System.Web.UI.WebControls.TextBox txtPost;
		protected global::System.Web.UI.WebControls.TextBox txtPhone;
		protected global::System.Web.UI.WebControls.TextBox txtGuideNo;
		protected global::System.Web.UI.WebControls.TextBox txtClient;
		protected global::System.Web.UI.WebControls.TextBox txtSalesperson;
		protected global::System.Web.UI.WebControls.TextBox txtTypes;
		protected global::System.Web.UI.WebControls.TextBox txtTips;
		protected global::System.Web.UI.WebControls.TextBox txtEntryTime;
		protected global::System.Web.UI.WebControls.TextBox txtEmbassyTime;
		protected global::System.Web.UI.WebControls.TextBox txtInTime;
		protected global::System.Web.UI.WebControls.TextBox txtOutTime;
		protected global::System.Web.UI.WebControls.TextBox txtRealOut;
		protected global::System.Web.UI.WebControls.TextBox txtRealOutTime;
		protected global::System.Web.UI.WebControls.TextBox txtCountry;
		protected global::System.Web.UI.WebControls.TextBox txtCall;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
