//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravletAgence.Web.VisaInfo {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblVisaInfo_id;
	protected global::System.Web.UI.WebControls.Label lblVisa_id;
	protected global::System.Web.UI.WebControls.Label lblGroupNo;
	protected global::System.Web.UI.WebControls.Label lblName;
	protected global::System.Web.UI.WebControls.Label lblEnglishName;
	protected global::System.Web.UI.WebControls.Label lblSex;
	protected global::System.Web.UI.WebControls.Label lblBirthday;
	protected global::System.Web.UI.WebControls.Label lblPassportNo;
	protected global::System.Web.UI.WebControls.Label lblLicenceTime;
	protected global::System.Web.UI.WebControls.Label lblExpiryDate;
	protected global::System.Web.UI.WebControls.Label lblBirthplace;
	protected global::System.Web.UI.WebControls.Label lblIssuePlace;
	protected global::System.Web.UI.WebControls.Label lblPost;
	protected global::System.Web.UI.WebControls.Label lblPhone;
	protected global::System.Web.UI.WebControls.Label lblGuideNo;
	protected global::System.Web.UI.WebControls.Label lblClient;
	protected global::System.Web.UI.WebControls.Label lblSalesperson;
	protected global::System.Web.UI.WebControls.Label lblTypes;
	protected global::System.Web.UI.WebControls.Label lblSale_id;
	protected global::System.Web.UI.WebControls.Label lblDepartmentId;
	protected global::System.Web.UI.WebControls.Label lblTips;
	protected global::System.Web.UI.WebControls.Label lblEntryTime;
	protected global::System.Web.UI.WebControls.Label lblEmbassyTime;
	protected global::System.Web.UI.WebControls.Label lblInTime;
	protected global::System.Web.UI.WebControls.Label lblOutTime;
	protected global::System.Web.UI.WebControls.Label lblRealOut;
	protected global::System.Web.UI.WebControls.Label lblRealOutTime;
	protected global::System.Web.UI.WebControls.Label lblCountry;
	protected global::System.Web.UI.WebControls.Label lblCall;


       
    }
}
